In [3]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [6]:
fear_greed=pd.read_csv(r"C:\phone\Desktop\Trader_Sentiment_Analysis\datasets\fear_greed_index.csv")
historical=pd.read_csv(r"C:\phone\Desktop\Trader_Sentiment_Analysis\datasets\historical_data.csv")

In [9]:
fear_greed.head()
fear_greed.tail()

       timestamp  value classification        date
2639  1745818200     54        Neutral  28-04-2025
2640  1745904600     60          Greed  29-04-2025
2641  1745991000     56          Greed  30-04-2025
2642  1746077400     53        Neutral  01-05-2025
2643  1746163800     67          Greed  02-05-2025

In [10]:
historical.head()
historical.tail()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,382.2,420.80,SELL,25-04-2025 15:35,7546.6,Close Long,-20.2566,0xcd339c08dc7b615a993c0422374d8e02027400092bc2...,88803313862,False,0.042080,1.990000e+14,1.750000e+12
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,2124.1,2338.63,SELL,25-04-2025 15:35,7164.4,Close Long,-112.5773,0x29e8ede2a3a37aa0eac00422374d8e02029b00ac9f3c...,88803313862,False,0.233863,9.260000e+14,1.750000e+12
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,423.4,466.16,SELL,25-04-2025 15:35,5040.3,Close Long,-22.4402,0x0780085b0c0a943eea800422374d920204c100edf579...,88803313862,False,0.046616,6.930000e+14,1.750000e+12
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,3599.8,3963.38,SELL,25-04-2025 15:35,4616.9,Close Long,-190.7894,0x349c29934913b25c89e20422374d920204cd008b8a0e...,88803313862,False,0.396337,4.180000e+14,1.750000e+12
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,1017.1,1119.83,SELL,25-04-2025 15:35,1017.1,Close Long,-53.9063,0xac77fab973c455d77a670422374d9602039800f1f78c...,88803313862,False,0.111982,3.270000e+14,1.750000e+12

In [14]:
fear_greed.columns

Index(['timestamp', 'value', 'classification', 'date'], dtype='str')

In [15]:
historical.columns

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='str')

In [17]:
fear_greed.info()

<class 'pandas.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   str
 3   date            2644 non-null   str
dtypes: int64(2), str(2)
memory usage: 82.8 KB

In [21]:
historical.info()

<class 'pandas.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  str
 1   Coin              211224 non-null  str
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  str
 6   Timestamp IST     211224 non-null  str
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  str
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  str
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), str(6)
memory usage: 24.4 MB

In [24]:
fear_greed['date']=pd.to_datetime(fear_greed['date'],
dayfirst=True).dt.date

In [26]:
historical['date'] = pd.to_datetime(
    historical['Timestamp IST'],
    dayfirst=True
).dt.date

In [27]:
fear_greed['date'].head()

0    2018-02-01
1    2018-02-02
2    2018-02-03
3    2018-02-04
4    2018-02-05
Name: date, dtype: object

In [32]:
merged=pd.merge(fear_greed,historical,on='date',how='inner')
merged.head()

,timestamp,value,classification,date,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,1682919000,63,Greed,2023-05-01,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1897.9,0.0967,183.53,BUY,01-05-2023 01:06,0.0000,Open Long,0.0,0x875d3e1af52b5b758e4f04015b774e0111006a118601...,173271100,True,0.000000,0.000000e+00,1.680000e+12
1,1682919000,63,Greed,2023-05-01,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1897.9,0.0824,156.39,BUY,01-05-2023 01:06,0.0967,Open Long,0.0,0x875d3e1af52b5b758e4f04015b774e0111006a118601...,173271100,True,0.000000,0.000000e+00,1.680000e+12
2,1682919000,63,Greed,2023-05-01,0x3998f134d6aaa2b6a5f723806d00fd2bbbbce891,ETH,1898.6,0.0722,137.08,BUY,01-05-2023 01:06,0.1791,Open Long,0.0,0x875d3e1af52b5b758e4f04015b774e0111006a118601...,173271100,True,0.000000,0.000000e+00,1.680000e+12
3,1701754200,75,Extreme Greed,2023-12-05,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,ETH,2230.1,0.4933,1100.11,BUY,05-12-2023 03:11,0.0000,Open Long,0.0,0x02721e3c6061bddfdc1204065f9dfe0138003649ef8c...,4064960965,True,0.275027,6.320000e+14,1.700000e+12
4,1701754200,75,Extreme Greed,2023-12-05,0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23,ETH,2230.1,0.8681,1935.95,BUY,05-12-2023 03:11,0.4933,Open Long,0.0,0x02721e3c6061bddfdc1204065f9dfe0138003649ef8c...,4064960965,True,0.483987,2.340000e+14,1.700000e+12

In [34]:
merged.size

4224360

In [37]:
merged['win']=merged['Closed PnL']>0
print(merged['win'])

0         False
1         False
2         False
3         False
4         False
          ...
211213    False
211214    False
211215    False
211216    False
211217    False
Name: win, Length: 211218, dtype: bool

In [40]:
merged.groupby('classification')['Closed PnL'].mean()

classification
Extreme Fear     34.537862
Extreme Greed    67.892861
Fear             54.290400
Greed            42.743559
Neutral          34.307718
Name: Closed PnL, dtype: float64

In [41]:
merged.groupby('classification')['win'].mean()

classification
Extreme Fear     0.370607
Extreme Greed    0.464943
Fear             0.420768
Greed            0.384828
Neutral          0.396991
Name: win, dtype: float64

In [42]:
merged.groupby('classification')['Size USD'].mean()

classification
Extreme Fear     5349.731843
Extreme Greed    3112.251565
Fear             7816.109931
Greed            5736.884375
Neutral          4782.732661
Name: Size USD, dtype: float64

In [50]:
merged.groupby(['classification','Direction']).size()

classification  Direction
Extreme Fear    Buy                            807
                Close Long                    6241
                Close Short                   3117
                Long > Short                     5
                Open Long                     7005
                Open Short                    3174
                Sell                          1042
                Short > Long                     6
                Spot Dust Conversion             3
Extreme Greed   Buy                           5132
                Close Long                    7186
                Close Short                   6497
                Long > Short                     7
                Open Long                     6300
                Open Short                    7663
                Sell                          7164
                Short > Long                    11
                Spot Dust Conversion            32
Fear            Buy                           3207
                Close Long                   17260
                Close Short                   9221
                Long > Short                    14
                Open Long                    17824
                Open Short                   10887
                Sell                          3364
                Short > Long                    18
                Spot Dust Conversion            42
Greed           Auto-Deleveraging                8
                Buy                           4685
                Close Long                    7998
                Close Short                  11322
                Liquidated Isolated Short        1
                Long > Short                    16
                Open Long                     8544
                Open Short                   11664
                Sell                          5986
                Settlement                       1
                Short > Long                    23
                Spot Dust Conversion            55
Neutral         Buy                           2885
                Close Long                    9993
                Close Short                   5850
                Long > Short                    15
                Open Long                    10222
                Open Short                    6353
                Sell                          2346
                Short > Long                    12
                Spot Dust Conversion            10
dtype: int64